version: '3.7'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
    volumes:
      - $PWD/caddy/Caddyfile.local:/etc/caddy/Caddyfile
      - frontend_build:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  mysql:
    platform: linux/amd64
    build:
      context: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - myqsl_db:/var/lib/mysql

  frontend:
    build:
      context: frontend
      args:
        NODE_ENV: production
        SERVER_DOMAIN: ${SERVER_DOMAIN}
    restart: "no"
    volumes:
      - frontend_build:/frontend

  backend:
    build:
      context: backend
    restart: always
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

volumes:
  caddy_data:
  caddy_config:
  frontend_build:
  myqsl_db:
